[package]
name = "ed25519blake2b"
version = "0.1.0"
authors = []

[lib]
name = "ed25519blake2b"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.20.0"
rustler_codegen = "0.20.0"
lazy_static = "1.0"
ed25519-dalek = "0.9"
blake2 = "0.8"
rand = "0.6"